version: '3.8'

services:
  db:
    image: postgres:15
    container_name: Hito5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_Hito5
    ports:
      - '5436:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
